services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.1
    container_name: keycloak
    command: start-dev
    ports:
      - "18080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    restart: always

  tdgen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tdgen
    ports:
      - "5200:5200"
    environment:
      - DATABASE_URL=file:/storage/prod.db
    volumes:
      - ./storage:/storage
    user: "1000:1000"
    restart: always
    command: npm run start:prod

volumes:
  keycloak_data:
