apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tdgen.fullname" . }}
  labels:
    {{- include "tdgen.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tdgen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tdgen.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tdgen.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: tdgen-storage
              mountPath: "/storage"
          env:
            - name: NODE_EXTRA_CA_CERTS
              value: /etc/ssl/certs/ca-certificates.crt
            - name: APP_HTTP_PORT
              value: {{ .Values.tdgen.appPort | quote }}
            - name: DATABASE_URL
              value: {{ .Values.tdgen.databaseURL | quote }}
            - name: TDGEN_USER_ATTR_NAME
              value: {{ .Values.tdgen.userGroupName | quote }}
            - name: TDGEN_ADMIN_ATTR_NAME
              value: {{ .Values.tdgen.adminGroupName | quote }}
            - name: JWT_SECRET
              value: {{ .Values.tdgen.jwtSecret | quote }}
            - name: SAML_METADATA_URL
              value: {{ .Values.tdgen.samlMetadataUrl | quote }}
            - name: SAML_CALLBACK_URL
              value: {{ .Values.tdgen.samlCallbackUrl | quote }}
            - name: SAML_ISSUER
              value: {{ .Values.tdgen.samlIssuer | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.tdgen.appPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tdgen-storage
      {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "tdgen.fullname" .) }}
      {{- else }}
          emptyDir: {}
      {{- end -}}
      {{- range .Values.extraVolumeMounts }}
        - name: {{ .name }}
          {{- if .existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .existingClaim }}
          {{- else if .hostPath }}
          hostPath:
            path: {{ .hostPath }}
          {{- else if .configMap }}
          configMap:
            name: {{ .configMap }}
            {{- with .items }}
            items:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- end }}
      {{- range .Values.extraEmptyDirMounts }}
        - name: {{ .name }}
          emptyDir: {}
      {{- end -}}
