{{- if not .Values.mongodb.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tdgen.mongodb.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "tdgen.mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mongodb.password }}
  mongodb-password: {{ .Values.mongodb.password | b64enc | quote }}
  {{- else }}
  mongodb-password: {{ randAlphaNum 15 | b64enc | quote }}
  {{- end }}
{{- end }}
